llm:
  provider: openai
  model: gpt-4
  api_key: ${OPENAI_API_KEY}
  temperature: 0.7
  max_tokens: 2000

metrics:
  provider: prometheus
  url: http://localhost:9090
  timeout: 1800

logging:
  level: INFO
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: logs/srex.log

templates_dir: templates
output_dir: output 